### ISSUE TITLE
Jenkins X application build step error

### ISSUE THREAD

**Issue by leandromoreirati** [PacktPublishing/Hands-On-Continuous-Integration-and-Delivery-with-Jenkins-X-and-Kubernetes#3]
When I run the applications that are in the examples in section 2 video-2.1 and video-2.2, I get the error below in the stage from-build-pack:
 
```
waiting for stage from-build-pack : container step-promote-helm-release to start...


Showing logs for build leandromoreirati/express-hello/master #1 stage from-build-pack and container step-promote-helm-release
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
error: failed to build dependencies for chart from directory '.': failed to add chart repositories: failed to add the Helm repository with URL 'https://storage.googleapis.com/chartmuseum.jenkins-x.io': failed to add the repository 'storage.googleapis.com' with URL 'https://storage.googleapis.com/chartmuseum.jenkins-x.io': failed to run 'helm repo add storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io' command in directory '.', output: 'Error: Couldn't load repositories file (/tekton/home/.helm/repository/repositories.yaml).
You might need to run `helm init` (or `helm init --client-only` if tiller is already installed)'

Pipeline failed on stage 'from-build-pack' : container 'step-promote-helm-release'. The execution of the pipeline has stopped.
```

I already searched the internet and I couldn't identify what I'm doing wrong will they be able to help me, below is the link with the complete error log:

https://gist.github.com/leandromoreirati/19461977b05b3af92f82e5c2d066992c

helm version
Client: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.9", GitCommit:"8ad7037828e5a0fca1009dabe290130da6368e39", GitTreeState:"clean"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.15", GitCommit:"2adc8d7091e89b6e3ca8d048140618ec89b39369", GitTreeState:"clean", BuildDate:"2020-09-02T11:40:00Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.15-gke.4901", GitCommit:"7ed5ddc0e67cb68296994f0b754cec45450d6a64", GitTreeState:"clean", BuildDate:"2020-11-06T18:22:22Z", GoVersion:"go1.13.15b4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by leandromoreirati** [comment]
Hello,
Yesterday I continued researching about the problem I reported in this issue and from what I discovered it is a problem in Jenkins X according to this issue [7597 ](https://github.com/jenkins-x/jx/issues/7597) opened in the project.

**Comment by AlanHohn** [comment]
Thanks. I'm glad you were able to identify the issue. It looks like others have posted opportunities for workaround. I will go ahead and close this.
